export interface IColors {
  PRIMARY_COLOR: string;
  SECONDARY_COLOR: string;
  PRIMARY_TEXT_COLOR: string;
  SECONDARY_TEXT_COLOR: string;
  BODY_BACKGROUND_COLOR: string;
  NAVBAR_BACKGROUND_COLOR: string;
  BORDER_COLOR: string;
  INPUT_BACKGROUND_COLOR: string;
  WHITE_COLOR: string;
  SUCCESS_COLOR: string;
  ERROR_COLOR: string;
}

const COMMON_COLORS = {
  PRIMARY_COLOR: '#4F48EC',
  SUCCESS_COLOR: '#31A24C',
  ERROR_COLOR: '#FC3930',
  WHITE_COLOR: '#FFF',
};

export const DARK_COLORS: IColors = {
  ...COMMON_COLORS,
  SECONDARY_COLOR: '#2F2F2F',
  PRIMARY_TEXT_COLOR: '#E4E6EB',
  SECONDARY_TEXT_COLOR: '#B0B3B8',
  BODY_BACKGROUND_COLOR: '#18191A',
  NAVBAR_BACKGROUND_COLOR: '#232323',
  BORDER_COLOR: '#3E4042',
  INPUT_BACKGROUND_COLOR: '#3A3B3C',
};

export const LIGHT_COLORS: IColors = {
  ...COMMON_COLORS,
  SECONDARY_COLOR: '#E4E6EB',
  PRIMARY_TEXT_COLOR: '#050505',
  SECONDARY_TEXT_COLOR: '#65676B',
  BODY_BACKGROUND_COLOR: '#F0F2F5',
  NAVBAR_BACKGROUND_COLOR: '#E4E6EB',
  BORDER_COLOR: '#CED0D4',
  INPUT_BACKGROUND_COLOR: '#E4E6EB',
};
